import { type QueryRunner } from 'typeorm';

import { AddFormulaFieldHistoryFastInstanceCommand } from 'src/database/commands/upgrade-version-command/2-26/2-26-instance-command-fast-1785434417770-add-formula-field-history';

describe('AddFormulaFieldHistoryFastInstanceCommand', () => {
  const query = jest.fn();
  const queryRunner = { query } as unknown as QueryRunner;
  const command = new AddFormulaFieldHistoryFastInstanceCommand();

  beforeEach(() => {
    jest.clearAllMocks();
  });

  it('creates an append-only ordered history ledger with origin checks', async () => {
    await command.up(queryRunner);

    expect(query).toHaveBeenCalledTimes(3);
    expect(query.mock.calls[0][0]).toContain(
      'CREATE TABLE "core"."formulaFieldHistory"',
    );
    expect(query.mock.calls[0][0]).toContain(
      '"sequence" bigint GENERATED BY DEFAULT AS IDENTITY',
    );
    expect(query.mock.calls[0][0]).toContain(
      'CHECK ("origin" IN (\'FIELD\', \'FORMULA\'))',
    );
    expect(query.mock.calls[2][0]).toContain(
      'CREATE INDEX "IDX_FORMULA_FIELD_HISTORY_LOOKUP"',
    );
  });

  it('drops only the Formula history table on rollback', async () => {
    await command.down(queryRunner);

    expect(query).toHaveBeenCalledWith(
      'DROP TABLE IF EXISTS "core"."formulaFieldHistory"',
    );
  });
});
