import { type QueryRunner } from 'typeorm';

import { RegisteredInstanceCommand } from 'src/engine/core-modules/upgrade/decorators/registered-instance-command.decorator';
import { type FastInstanceCommand } from 'src/engine/core-modules/upgrade/interfaces/fast-instance-command.interface';

@RegisteredInstanceCommand('2.26.0', 1785434417770)
export class AddFormulaFieldHistoryFastInstanceCommand
  implements FastInstanceCommand
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "core"."formulaFieldHistory" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "sequence" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "workspaceId" uuid NOT NULL,
        "objectMetadataId" uuid NOT NULL,
        "recordId" uuid NOT NULL,
        "fieldMetadataId" uuid NOT NULL,
        "origin" character varying NOT NULL,
        "formulaDefinitionId" uuid,
        "formulaVersionId" uuid,
        "evaluationReceiptId" uuid,
        "eventKey" character varying(64) NOT NULL,
        "beforeValue" jsonb,
        "afterValue" jsonb,
        "actorUserId" uuid,
        "actorWorkspaceMemberId" uuid,
        "effectiveAt" TIMESTAMP WITH TIME ZONE NOT NULL,
        "observedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
        "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_FORMULA_FIELD_HISTORY" PRIMARY KEY ("id"),
        CONSTRAINT "CHK_FORMULA_FIELD_HISTORY_ORIGIN"
          CHECK ("origin" IN ('FIELD', 'FORMULA')),
        CONSTRAINT "CHK_FORMULA_FIELD_HISTORY_FORMULA_ORIGIN"
          CHECK (
            ("origin" = 'FIELD' AND "formulaDefinitionId" IS NULL AND "formulaVersionId" IS NULL)
            OR
            ("origin" = 'FORMULA' AND "formulaDefinitionId" IS NOT NULL AND "formulaVersionId" IS NOT NULL)
          ),
        CONSTRAINT "FK_FORMULA_FIELD_HISTORY_WORKSPACE"
          FOREIGN KEY ("workspaceId") REFERENCES "core"."workspace"("id") ON DELETE CASCADE,
        CONSTRAINT "FK_FORMULA_FIELD_HISTORY_OBJECT"
          FOREIGN KEY ("objectMetadataId") REFERENCES "core"."objectMetadata"("id") ON DELETE CASCADE,
        CONSTRAINT "FK_FORMULA_FIELD_HISTORY_FIELD"
          FOREIGN KEY ("fieldMetadataId") REFERENCES "core"."fieldMetadata"("id") ON DELETE CASCADE,
        CONSTRAINT "IDX_FORMULA_FIELD_HISTORY_EVENT_KEY_UNIQUE"
          UNIQUE ("workspaceId", "eventKey")
      )
    `);
    await queryRunner.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS "IDX_FORMULA_FIELD_HISTORY_SEQUENCE_UNIQUE"
      ON "core"."formulaFieldHistory" ("sequence")
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "IDX_FORMULA_FIELD_HISTORY_LOOKUP"
      ON "core"."formulaFieldHistory"
      ("workspaceId", "objectMetadataId", "recordId", "fieldMetadataId", "effectiveAt", "sequence")
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      'DROP TABLE IF EXISTS "core"."formulaFieldHistory"',
    );
  }
}
